### PR TITLE
fix issue #43

### PR DESCRIPTION
**Pull request by Wikinaut**
* add a start code, and installDeps.sh in new subdirectory bin/run.sh
* start as "sudo -u mediathekviewweb (mediathekviewwebroot)/bin/run.sh"

Tested. Works for me.

@bagbag Check https://github.com/ether/etherpad-lite/blob/develop/bin/installDeps.sh for further ideas what can be checked !

### CODE REVIEW

**Comment by bagbag** [comment]
It's actually not suitable for my server-setup, as I am using [pm2](https://github.com/Unitech/pm2).

Also, it actually doesn't fix #43. It's about transpiling index.js whenever you save it. What's needed is for example a script we start on dev-begin doing `babel-cli --watch` [https://babeljs.io/docs/usage/cli/](https://babeljs.io/docs/usage/cli/).

**Comment by bagbag** [comment]
Another idea: as `npm install` & `npm run build` is only needed once, I suggest creating an update.sh pulling master from git and running these commands.

**Comment by Wikinaut** [comment]
This all is now up to you. I just wanted to show you quickly my ad-hoc solution, mercilessly borrowed and copied from Etherpad. If you want: please simply close my pull requests.

**Comment by bagbag** [comment]
No. The idea is good (it just doesn't fit my usecase). If you remove installDeps from run, I'll try it out and will merge it.
Actually update.sh is not needed, as it's git clone and install deps. And if it's not obtained via git, its useless.

**Pull request closed without merging**
